# Generated by Django 4.2 on 2025-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_notification',
            field=models.BooleanField(default=True, help_text='通知メールを送るかを示します', verbose_name='notification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='login id'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_password',
            field=models.CharField(blank=True, max_length=150, verbose_name='login password'),
        ),
    ]
