# Generated by Django 4.2 on 2025-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_is_notification_customuser_login_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_notification',
            field=models.BooleanField(default=True, help_text='通知メールを送るかどうかを示します', verbose_name='通知'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='ログインID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login_password',
            field=models.CharField(blank=True, max_length=150, verbose_name='ログインパスワード'),
        ),
    ]
